name: CI/CD Workflow (services/articles-management)

on:
    push:
      paths: 
        - 'services/articles-management'
      branches:
        - develop
        - master
  
    pull_request:
      paths: 
        - 'services/articles-management'
      branches:
        - develop
        - master

jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.base_ref == 'develop'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Run npm install
        run: cd services/articles-management && npm install

      - name: Run npm lint
        run: cd services/articles-management && npm run lint

  build_and_push_docker:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker image
        run: |
          cd services/articles-management && VERSION=$(jq -r .version < package.json)
          docker build -t ${{ secrets.DOCKER_USERNAME }}/articles-management:v$VERSION .
  
      - name: Push Docker image
        run: |
         cd services/articles-management && VERSION=$(jq -r .version < package.json)
         docker push ${{ secrets.DOCKER_USERNAME }}/articles-management:v$VERSION